---
- name: Ensure Supervisor config paths are present.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ supervisor_config_path }}"
    - "{{ supervisor_config_path }}/conf.d"
    - "{{ supervisor_config_path }}/conf.d/groups"

- name: Ensure Supervisor configuration is present.
  template:
    src: supervisord.conf.j2
    dest: "{{ supervisor_config_path }}/supervisord.conf"
    mode: 0644
  notify: Restart supervisord

- name: Ensure Supervisor program configs are present.
  template:
    src: program.conf.j2
    dest: "{{ supervisor_config_path }}/conf.d/{{ item.name }}.conf"
    force: yes
    owner: root
    group: root
    mode: 0644
  when: item.state|default('present') != 'absent'
  with_items: "{{ supervisor_programs }}"
  notify: Reload supervisord config

- name: Ensure Supervisor group configs are present.
  template:
    src: group.conf.j2
    dest: "{{ supervisor_config_path }}/conf.d/groups/{{ item.name }}.conf"
    force: yes
    owner: root
    group: root
    mode: 0644
  when: item.state|default('present') != 'absent'
  with_items: "{{ supervisor_groups }}"
  notify: Reload supervisord config
